const scenes = [
  {
    name: 'FMS_FULL',
    description:
      'Used whenever the output is a full-screen display that showing from FMS, such as the messages generated by the scorekeeper. It should contain the Chroma filter.',
  },
  {
    name: 'FMS_HIDDEN',
    description:
      'Used whenever the FMS Audience Display is not supposed to be seen, or has finished showing data. For example, after showing match preview.',
  },
  {
    name: 'FMS_SCORE',
    description:
      'Used during Match Play. It must, at minimum, show the score bar generated by FMS. It should contain the Chroma filter.',
  },
  {
    name: 'FMS_RESULT',
    description: 'Used during the Post Result after a match.',
  },
  {
    name: 'FMS_ALLIANCE',
    description:
      'Used during the Alliance Selection. It should contain the Chroma filter if using the Alliance Hybrid View.',
  },
  {
    name: 'FMS_AWARDS',
    description:
      'The output during Award Ceremonies. It should accommodate the lower third bar that shows the award being presented and the winning team. It should contain the Chroma filter.',
  },
] as const;

export type SceneName = (typeof scenes)[number]['name'];

export default scenes;
